name: ðŸ—£ï¸ Documentation Feedback
description: |
  This template is only meant to be used from the live page on https://learn.microsoft.com.

  If you're filing an issue on GitHub, please use one of the other templates.
labels:
  - needs-triage
body:
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: pageQueryParams
    validations:
      required: true
    attributes:
      label: Page URL query parameters
  - type: input
    id: documentId
    validations:
      required: true
    attributes:
      label: Document Id
  - type: textarea
    id: feedback
    validations:
      required: true
    attributes:
      label: Feedback
      description: >-
        Write a clear and concise description of your feedback for the documentation.
  - type: textarea
    id: details
    validations:
      required: false
    attributes:
      label: Details
      description: >-
        If possible, please provide extended details that will add context and help the team
        address your feedback.
